# Generated by Django 5.1.1 on 2024-10-20 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConcatUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxLengthValidator(11)])),
                ('body', models.TextField()),
            ],
        ),
    ]
