# Generated by Django 5.1.1 on 2024-10-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concatus',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
