# Generated by Django 5.1.1 on 2024-10-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_note',
            field=models.CharField(blank=True, max_length=700, verbose_name='Order Note'),
        ),
    ]
