# Generated by Django 5.1.1 on 2024-10-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product/product_cover', verbose_name='Product Image'),
        ),
    ]
